# Generated by Django 5.1.7 on 2025-04-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmapping',
            name='departmentid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='DepartmentId',
        ),
    ]
