# Generated by Django 5.2 on 2025-05-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_emailotpverification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
