# Generated by Django 5.2 on 2025-05-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_serviceprovider_business_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
