# Generated by Django 5.2 on 2025-04-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_serviceprovider_serviceproviderhighlights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='average_rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='service_provider/company_logo/', verbose_name='company_logo Image'),
        ),
    ]
