# Generated by Django 5.2 on 2025-05-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_serviceprovider_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='users/profile_picture/', verbose_name='profile_picture Image'),
        ),
    ]
