# Generated by Django 5.2 on 2025-04-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_delete_projectmapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='altername_mobile_number',
            new_name='alternate_mobile_number',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='company_logo',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='business_logo',
            field=models.FileField(blank=True, null=True, upload_to='service_provider/business_logo/', verbose_name='business_logo Image'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
