# Generated by Django 5.2 on 2025-05-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
