# Generated by Django 5.2 on 2025-04-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_rename_altername_mobile_number_serviceprovider_alternate_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderhighlights',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
