# Generated by Django 5.2 on 2025-04-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_serviceproviderhighlights_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='mozil_guaranteed',
            new_name='mozil_guarented',
        ),
    ]
