# Generated by Django 5.2 on 2025-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewsAndRating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsAndRatingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('viewedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('viewedAt', models.DateTimeField(blank=True, null=True)),
                ('service_provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('reviews_and_rating_id', models.CharField(blank=True, max_length=255, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='reviews_and_rating/media/', verbose_name='media Image')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reviewsandrating',
            name='service_provider_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
