# Generated by Django 5.2 on 2025-05-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewsAndRating', '0002_reviewsandratingmedia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsandrating',
            name='rating_count',
            field=models.FloatField(blank=True, max_length=250, null=True),
        ),
    ]
