# Generated by Django 5.2 on 2025-05-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewsAndRating', '0003_alter_reviewsandrating_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsandrating',
            name='rating_count',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
