# Generated by Django 5.2 on 2025-05-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementsmaster',
            name='action_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
