# Generated by Django 5.2 on 2025-05-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_childservices_description_childservices_icon_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentservices',
            name='featured_image',
            field=models.FileField(blank=True, null=True, upload_to='services/parent/featured_image/', verbose_name='featured Image'),
        ),
    ]
