# Generated by Django 5.2 on 2025-06-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_parentservices_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentservices',
            name='recomended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
