# Generated by Django 5.2 on 2025-04-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderplanmaster',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
